# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d970686aa77a497926a55db6c66b375e5eecda9414f7e2073dd4f51285bd1ef4e8039d1bb2919e201bc03d6c8853689ea2dc312f1f887d5cd375619e5347d3

test:
  secret_key_base: 05047afcc661c6e2f855d6d53cf4cdd838e54798a35df4630f38029f4f71b554234df70adf290df77a62bb13255349d69fa42479f19c5af317405644c3fc407c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
